/**
 * okno zprávy
 */
package JIM.client;

/**
 *
 * @author cypher
 */
public class MessageWindow extends javax.swing.JDialog {

    private Contact contact = null;

    /** Creates new form MessageWindow */
    public MessageWindow(java.awt.Frame parent, boolean modal, Contact c) {
        super(parent, modal);
        contact = c;
        setResizable(false);
        initComponents();
        addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                setVisible(false);
            }
        });

    }

    /**
     * zkontroluje aktualni stav kontaktu a pokud je offline, zakaze odesilani zprav
     */
    public void checkContactState() {
        if (contact.isOnline()) {
            send.setEnabled(true);
        } else {
            send.setEnabled(false);
        }

        notice.setText(contact.isOnline() ? "" : contact.getName() + " je offline.");
    }

    /**
     * vrati kontakt okenka
     * @return
     */
    public Contact getContact() {
        return contact;
    }

    /**
     * prida zpravu do logu
     * @param m
     */
    public void addMessage(Message m) {
        log.append(m.toString() + "\n");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        notice = new javax.swing.JLabel();
        send = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        log.setColumns(20);
        log.setEditable(false);
        log.setLineWrap(true);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        message.setColumns(20);
        message.setLineWrap(true);
        message.setRows(5);
        jScrollPane2.setViewportView(message);

        send.setText("Odeslat");
        send.setEnabled(false);
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(notice, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(send)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * akce po kliknuti na odeslat
     * @param evt
     */
    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        if (send.isEnabled()) {
            TCPConnection c = TCPConnection.getInstance();
            Message m = new Message(message.getText());
            m.setRecipient(contact);
            m.setType("out");
            c.send(m.toXMLString());
            message.setText(null);
            addMessage(m);
        }
    }//GEN-LAST:event_sendMouseClicked
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea log;
    private javax.swing.JTextArea message;
    private javax.swing.JLabel notice;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
